name: Migrate database

on:
  workflow_call:

jobs:
  check-new-migrations:
    runs-on: ubuntu-latest
    outputs:
      trigger-migration: ${{ steps.check-migrations.outputs.trigger-migration }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check if new migrations were added
        id: check-migrations
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q src/db-management/migrations; then
            echo "trigger-migration=true" >> $GITHUB_OUTPUT
          else
            echo "trigger-migration=false" >> $GITHUB_OUTPUT
          fi
  migrate-db:
    runs-on: ubuntu-latest
    needs: check-new-migrations
    if: ${{ needs.check-new-migrations.outputs.trigger-migration == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - name: Migrate database
        run: echo "I am migrating the database"
  skipping-migration:
    runs-on: ubuntu-latest
    needs: check-new-migrations
    if: ${{ needs.check-new-migrations.outputs.trigger-migration == 'false' }}
    steps:
      - name: Skipping migration
        run: echo "Skipping database migration"
